/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : Cpu.c
**     Project     : Proyecto_SOTR
**     Processor   : MC9S08PT60VLH
**     Component   : MC9S08PT60_64
**     Version     : Component 01.105, Driver 01.40, CPU db: 3.00.007
**     Datasheet   : MC9S08PT60RM Rev. 3 Draft A, 12/2011
**     Compiler    : CodeWarrior HCS08 C Compiler
**     Date/Time   : 2022-05-23, 15:07, # CodeGen: 70
**     Abstract    :
**         This component "MC9S08PT60_64" contains initialization 
**         of the CPU and provides basic methods and events for 
**         CPU core settings.
**     Settings    :
**
**     Contents    :
**         EnableInt  - void Cpu_EnableInt(void);
**         DisableInt - void Cpu_DisableInt(void);
**
**     Copyright : 1997 - 2014 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file Cpu.c
** @version 01.40
** @brief
**         This component "MC9S08PT60_64" contains initialization 
**         of the CPU and provides basic methods and events for 
**         CPU core settings.
*/         
/*!
**  @addtogroup Cpu_module Cpu module documentation
**  @{
*/         

/* MODULE Cpu. */

#pragma MESSAGE DISABLE C4002 /* WARNING C4002: Result not used is ignored */

#include "Led1.h"
#include "Led_button.h"
#include "Button.h"
#include "ADC1.h"
#include "PWM.h"
#include "Led2.h"
#include "Button_1.h"
#include "Led_ejemplo.h"
#include "MCUC1.h"
#include "WAIT1.h"
#include "GI2C1.h"
#include "EI2C1.h"
#include "DataPin1.h"
#include "ClockPin1.h"
#include "LCD1.h"
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "PE_Timer.h"
#include "Events.h"
#include "Cpu.h"


/* Global variables */
volatile byte CCR_reg;                 /* Current CCR register */
volatile byte CCR_lock;                /* Nesting level of critical regions */


/*
** ===================================================================
**     Method      :  Cpu_Interrupt (component MC9S08PT60_64)
**
**     Description :
**         The method services unhandled interrupt vectors.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
ISR(Cpu_Interrupt)
{
  /* This code can be changed using the CPU component property "Build Options / Unhandled int code" */
  /*lint -save -e950 Disable MISRA rule (1.1) checking. */
  asm(BGND);
  /*lint -restore Enable MISRA rule (1.1) checking. */
}


/*
** ===================================================================
**     Method      :  Cpu_DisableInt (component MC9S08PT60_64)
**     Description :
**         Disables maskable interrupts
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void Cpu_DisableInt(void)

**      This method is implemented as macro in the header module. **
*/

/*
** ===================================================================
**     Method      :  Cpu_EnableInt (component MC9S08PT60_64)
**     Description :
**         Enables maskable interrupts
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void Cpu_EnableInt(void)

**      This method is implemented as macro in the header module. **
*/

/*
** ===================================================================
**     Method      :  _EntryPoint (component MC9S08PT60_64)
**
**     Description :
**         Initializes the whole system like timing and so on. At the end 
**         of this function, the C startup is invoked to initialize stack,
**         memory areas and so on.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
extern void _Startup(void);            /* Forward declaration of external startup function declared in file Start12.c */

#pragma NO_FRAME
#pragma NO_EXIT
void _EntryPoint(void)
{
  /* ### MC9S08PT60_64 "Cpu" init code ... */
  /*  PE initialization code after reset */
  /* WDOG_CNT: CNT=0xC520 */
  setReg16(WDOG_CNT, 0xC520U);         /* First part of the WDG unlock sequence */ 
  /* WDOG_CNT: CNT=0xD928 */
  setReg16(WDOG_CNT, 0xD928U);         /* Second part of the WDG unlock sequence */ 
  /* WDOG_TOVAL: TOVAL=4 */
  setReg16(WDOG_TOVAL, 0x04U);          
  /* WDOG_CS2: WIN=0,FLG=0,??=0,PRES=0,??=0,??=0,CLK=1 */
  setReg8(WDOG_CS2, 0x01U);             
  /* WDOG_CS1: EN=0,INT=0,UPDATE=0,TST=0,DBG=0,WAIT=0,STOP=0 */
  setReg8(WDOG_CS1, 0x00U);            /* Disable watchdog */ 
  /* Common initialization of the write once registers */
  /* SYS_SOPT1: BKGDPE=1,RSTPE=1,FWAKE=0,STOPE=0 */
  clrSetReg8Bits(SYS_SOPT1, 0x03U, 0x0CU); 
  /* PMC_SPMSC1: LVWIE=0,LVDRE=1,LVDSE=1,LVDE=1,BGBDS=0,BGBE=0 */
  clrSetReg8Bits(PMC_SPMSC1, 0x23U, 0x1CU); 
  /* PMC_SPMSC2: LVDV=0,LVWV=0 */
  clrReg8Bits(PMC_SPMSC2, 0x70U);       
  /*  System clock initialization */
  /*lint -save  -e923 Disable MISRA rule (11.3) checking. */
  if (*(uint8_t*)0xFF6FU != 0xFFU) {   /* Test if the device trim value is stored on the specified address */
    ICS_C3 = *(uint8_t*)0xFF6FU;       /* Initialize ICS_C3 register from a non volatile memory */
    ICS_C4 = (uint8_t)((*(uint8_t*)0xFF6EU) & (uint8_t)0x01U); /* Initialize ICS_C4 register from a non volatile memory */
  }
  /*lint -restore Enable MISRA rule (11.3) checking. */
  /* ICS_C1: CLKS=0,RDIV=0,IREFS=1,IRCLKEN=1,IREFSTEN=0 */
  setReg8(ICS_C1, 0x06U);              /* Initialization of the ICS control register 1 */ 
  /* ICS_C2: BDIV=1,LP=0,??=0,??=0,??=0,??=0 */
  setReg8(ICS_C2, 0x20U);              /* Initialization of the ICS control register 2 */ 
  /* ICS_C4: LOLIE=0,CME=0 */
  clrReg8Bits(ICS_C4, 0xA0U);           

  /*** End of PE initialization code after reset ***/
  /*lint -save  -e950 Disable MISRA rule (1.1) checking. */
  __asm   jmp _Startup ;               /* Jump to C startup code */
  /*lint -restore Enable MISRA rule (1.1) checking. */
}

/*
** ===================================================================
**     Method      :  PE_low_level_init (component MC9S08PT60_64)
**
**     Description :
**         Initializes components and provides common register 
**         initialization. The method is called automatically as a part 
**         of the application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void PE_low_level_init(void)
{
  #ifdef PEX_RTOS_INIT
    PEX_RTOS_INIT();                   /* Initialization of the selected RTOS. Macro is defined by the RTOS component. */
  #endif
  /* SCG_C1: FTM2=1,FTM1=1,FTM0=1,??=0,??=0,MTIM1=1,MTIM0=1,RTC=1 */
  setReg8(SCG_C1, 0xE7U);               
  /* SCG_C2: ??=0,??=0,DBG=1,NVM=1,IPC=1,CRC=1,??=0,??=0 */
  setReg8(SCG_C2, 0x3CU);               
  /* SCG_C3: ??=0,SCI2=1,SCI1=1,SCI0=1,SPI1=1,SPI0=1,IIC=1,??=0 */
  setReg8(SCG_C3, 0x7EU);               
  /* SCG_C4: ACMP=1,??=0,ADC=1,??=0,IRQ=1,TSI=1,KBI1=1,KBI0=1 */
  setReg8(SCG_C4, 0xAFU);               
  /* Common initialization of the CPU registers */
  /* PORT_PTDD: PTDD0=0 */
  clrReg8Bits(PORT_PTDD, 0x01U);        
  /* PORT_PTDPE: PTDPE4=1,PTDPE0=0 */
  clrSetReg8Bits(PORT_PTDPE, 0x01U, 0x10U); 
  /* PORT_PTDOE: PTDOE4=0,PTDOE0=1 */
  clrSetReg8Bits(PORT_PTDOE, 0x10U, 0x01U); 
  /* PORT_PTDIE: PTDIE4=1,PTDIE0=0 */
  clrSetReg8Bits(PORT_PTDIE, 0x01U, 0x10U); 
  /* PORT_PTHD: PTHD0=1 */
  setReg8Bits(PORT_PTHD, 0x01U);        
  /* PORT_PTHPE: PTHPE0=0 */
  clrReg8Bits(PORT_PTHPE, 0x01U);       
  /* PORT_PTHOE: PTHOE0=1 */
  setReg8Bits(PORT_PTHOE, 0x01U);       
  /* PORT_PTHIE: PTHIE0=0 */
  clrReg8Bits(PORT_PTHIE, 0x01U);       
  /* ADC_APCTL1: ADPC6=1 */
  setReg8Bits(ADC_APCTL1, 0x40U);       
  /* ADC_APCTL2: ADPC9=1 */
  setReg8Bits(ADC_APCTL2, 0x02U);       
  /* PORT_PTBOE: PTBOE4=1 */
  setReg8Bits(PORT_PTBOE, 0x10U);       
  /* PORT_PTBD: PTBD4=0 */
  clrReg8Bits(PORT_PTBD, 0x10U);        
  /* PORT_PTGD: PTGD2=0,PTGD0=0 */
  clrReg8Bits(PORT_PTGD, 0x05U);        
  /* PORT_PTGPE: PTGPE2=0,PTGPE0=0 */
  clrReg8Bits(PORT_PTGPE, 0x05U);       
  /* PORT_PTGOE: PTGOE2=1,PTGOE0=1 */
  setReg8Bits(PORT_PTGOE, 0x05U);       
  /* PORT_PTGIE: PTGIE2=0,PTGIE0=0 */
  clrReg8Bits(PORT_PTGIE, 0x05U);       
  /* PORT_PTEPE: PTEPE4=1 */
  setReg8Bits(PORT_PTEPE, 0x10U);       
  /* PORT_PTEOE: PTEOE4=0 */
  clrReg8Bits(PORT_PTEOE, 0x10U);       
  /* PORT_PTEIE: PTEIE4=1 */
  setReg8Bits(PORT_PTEIE, 0x10U);       
  /* PORT_PTAD: PTAD7=1,PTAD6=1 */
  setReg8Bits(PORT_PTAD, 0xC0U);        
  /* PORT_PTAPE: PTAPE7=1,PTAPE6=1 */
  setReg8Bits(PORT_PTAPE, 0xC0U);       
  /* PORT_PTAOE: PTAOE7=0,PTAOE6=0 */
  clrReg8Bits(PORT_PTAOE, 0xC0U);       
  /* PORT_PTAIE: PTAIE7=1,PTAIE6=1 */
  setReg8Bits(PORT_PTAIE, 0xC0U);       
  /* SYS_SOPT3: CLKOE=0,BUSREF=0 */
  clrReg8Bits(SYS_SOPT3, 0x0FU);        
  /* IPC_ILRS9: ILRn3=0,ILRn2=0,ILRn1=0,ILRn0=0 */
  setReg8(IPC_ILRS9, 0x00U);            
  /* IPC_ILRS8: ILRn3=0,ILRn2=0,ILRn1=0,ILRn0=0 */
  setReg8(IPC_ILRS8, 0x00U);            
  /* IPC_ILRS7: ILRn3=0,ILRn2=0,ILRn1=0,ILRn0=0 */
  setReg8(IPC_ILRS7, 0x00U);            
  /* IPC_ILRS6: ILRn3=0,ILRn2=0,ILRn1=0,ILRn0=0 */
  setReg8(IPC_ILRS6, 0x00U);            
  /* IPC_ILRS5: ILRn3=0,ILRn2=2,ILRn1=0,ILRn0=0 */
  setReg8(IPC_ILRS5, 0x20U);            
  /* IPC_ILRS4: ILRn3=0,ILRn2=0,ILRn1=0,ILRn0=0 */
  setReg8(IPC_ILRS4, 0x00U);            
  /* IPC_ILRS3: ILRn3=0,ILRn2=0,ILRn1=0,ILRn0=0 */
  setReg8(IPC_ILRS3, 0x00U);            
  /* IPC_ILRS2: ILRn3=0,ILRn2=0,ILRn1=0,ILRn0=0 */
  setReg8(IPC_ILRS2, 0x00U);            
  /* IPC_ILRS1: ILRn3=0,ILRn2=0,ILRn1=0,ILRn0=0 */
  setReg8(IPC_ILRS1, 0x00U);            
  /* IPC_ILRS0: ILRn3=0,ILRn2=0,ILRn1=0,ILRn0=0 */
  setReg8(IPC_ILRS0, 0x00U);            
  /* IPC_SC: IPCE=1,??=0,PSE=0,PSF=0,PULIPM=0,??=0,IPM=0 */
  setReg8(IPC_SC, 0x80U);               
      /* Initialization of the PORT module */
  /* ### Shared modules init code ... */
  /* ### BitIO "Led1" init code ... */
  /* ### BitIO "Led_button" init code ... */
  /* ### BitIO "Button" init code ... */
  /* ###  "ADC1" init code ... */
  ADC1_Init();
  /* ### Programable pulse generation "PWM" init code ... */
  PWM_Init();
  /* ### BitIO "Led2" init code ... */
  /* ### BitIO "Button_1" init code ... */
  /* ### BitIO "Led_ejemplo" init code ... */
  MCUC1_Init(); /* ### McuLibConfig "MCUC1" init code ... */
  WAIT1_Init(); /* ### Wait "WAIT1" init code ... */
  /* ### BitIO "DataPin1" init code ... */
  /* ### BitIO "ClockPin1" init code ... */
  /* ###  "EI2C1" init code ... */
  EI2C1_Init();
  GI2C1_Init(); /* ### GenericI2C "GI2C1" init code ... */
#if LCD1_CONFIG_INITIALIZE_IN_INIT
  LCD1_Init(); /* ### SSD1306 "LCD1" init code ... */
#endif
  CCR_lock = (byte)0;
  __EI();                              /* Enable interrupts */
}

/*lint -save  -e950 Disable MISRA rule (1.1) checking. */
/* Initialization of the CPU registers in FLASH */
/*lint -restore Enable MISRA rule (1.1) checking. */

/* END Cpu. */

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.09]
**     for the Freescale HCS08 series of microcontrollers.
**
** ###################################################################
*/
