/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : DataPin1.c
**     Project     : Proyecto_SOTR
**     Processor   : MC9S08PT60VLH
**     Component   : BitIO
**     Version     : Component 02.086, Driver 03.27, CPU db: 3.00.007
**     Compiler    : CodeWarrior HCS08 C Compiler
**     Date/Time   : 2022-05-17, 12:50, # CodeGen: 57
**     Abstract    :
**         This component "BitIO" implements an one-bit input/output.
**         It uses one bit/pin of a port.
**         Note: This component is not set in the "Safe mode". See help.
**         Methods of this component are mostly implemented as a macros
**         (if supported by target language and compiler).
**     Settings    :
**         Used pin                    :
**             ----------------------------------------------------
**                Number (on package)  |    Name
**             ----------------------------------------------------
**                       38            |  PTA6_FTM2FAULT1_ADP2_TSI0
**             ----------------------------------------------------
**
**         Port name                   : PTA
**
**         Bit number (in port)        : 6
**         Bit mask of the port        : $0040
**
**         Initial direction           : Input (direction can be changed)
**         Safe mode                   : no
**         Initial output value        : 1
**         Initial pull option         : up
**
**         Port data register          : PORT_PTAD [$0000]
**         Port control register       : PORT_PTAOE [$30B0]
**
**         Optimization for            : speed
**     Contents    :
**         SetDir - void DataPin1_SetDir(bool Dir);
**         GetVal - bool DataPin1_GetVal(void);
**         ClrVal - void DataPin1_ClrVal(void);
**         SetVal - void DataPin1_SetVal(void);
**
**     Copyright : 1997 - 2014 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file DataPin1.c
** @version 03.27
** @brief
**         This component "BitIO" implements an one-bit input/output.
**         It uses one bit/pin of a port.
**         Note: This component is not set in the "Safe mode". See help.
**         Methods of this component are mostly implemented as a macros
**         (if supported by target language and compiler).
*/         
/*!
**  @addtogroup DataPin1_module DataPin1 module documentation
**  @{
*/         

/* MODULE DataPin1. */

#include "DataPin1.h"
  /* Including shared modules, which are used in the whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "PE_Timer.h"
#include "Cpu.h"


/*
** ===================================================================
**     Method      :  DataPin1_GetVal (component BitIO)
**     Description :
**         This method returns an input value.
**           a) direction = Input  : reads the input value from the
**                                   pin and returns it
**           b) direction = Output : returns the last written value
**     Parameters  : None
**     Returns     :
**         ---             - Input value. Possible values:
**                           FALSE - logical "0" (Low level)
**                           TRUE - logical "1" (High level)

** ===================================================================
*/
bool DataPin1_GetVal(void)
{
  return (bool)((getReg8(PORT_PTAD) & 0x40U)); /* Return port data */
}

/*
** ===================================================================
**     Method      :  DataPin1_ClrVal (component BitIO)
**     Description :
**         This method clears (sets to zero) the output value.
**         Note: If direction is set to input the method code may not
**               work properly.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void DataPin1_ClrVal(void)
{
  clrReg8Bits(PORT_PTAD, 0x40U);       /*  */
}

/*
** ===================================================================
**     Method      :  DataPin1_SetVal (component BitIO)
**     Description :
**         This method sets (sets to one) the output value.
**         Note: If direction is set to input the method code may not
**               work properly.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void DataPin1_SetVal(void)
{
  setReg8Bits(PORT_PTAD, 0x40U);       /*  */
}

/*
** ===================================================================
**     Method      :  DataPin1_SetDir (component BitIO)
**     Description :
**         This method sets direction of the component.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Dir        - Direction to set (FALSE or TRUE)
**                      FALSE = Input, TRUE = Output
**     Returns     : Nothing
** ===================================================================
*/
void DataPin1_SetDir(bool Dir)
{
  if (Dir) {
    setReg8Bits(PORT_PTAOE, 0x40U);    /* PTAOE6=0x01U */
    clrReg8Bits(PORT_PTAIE, 0x40U);    /* PTAIE6=0x00U */
  } else { /* !Dir */
    clrReg8Bits(PORT_PTAOE, 0x40U);    /* PTAOE6=0x00U */
    setReg8Bits(PORT_PTAIE, 0x40U);    /* PTAIE6=0x01U */
  } /* !Dir */
}


/* END DataPin1. */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.09]
**     for the Freescale HCS08 series of microcontrollers.
**
** ###################################################################
*/
